on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  workflow_dispatch:


jobs:
  lint_and_format_check:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          npm install
          npm run lint
          npm run format:check

  run_tests:
    name: Run Tests
    needs: lint_and_format_check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          npm install
          npm run test:ci
        env:
          PALM_APIKEY=${{ secrets.PALM_APIKEY }}

  publish:
    needs: run_tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci && npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
      - name: "Create a GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
